# Ada-style Knowledge Graph
# Each condition maps to a dict of {symptom: weight}.
# Weights are in range [0.0, 1.0] and represent diagnostic sensitivity
# of that symptom for the condition.
#
# This is NOT if-else. It is weighted reasoning.
# The inference engine sums weights for matching symptoms → produces a score.

CONDITIONS: dict[str, dict[str, float]] = {
    "viral_fever": {
        "fever": 0.9,
        "fatigue": 0.6,
        "cough": 0.4,
        "body_ache": 0.5,
        "headache": 0.4,
        "chills": 0.5,
        "sore_throat": 0.3,
    },
    "pneumonia_risk": {
        "fever": 0.8,
        "cough": 0.7,
        "breathlessness": 0.9,
        "chest_pain": 0.6,
        "fatigue": 0.5,
        "chills": 0.4,
    },
    "common_cold": {
        "nasal_congestion": 0.9,
        "sore_throat": 0.7,
        "cough": 0.6,
        "headache": 0.4,
        "fatigue": 0.3,
        "fever": 0.2,
    },
    "influenza": {
        "fever": 0.85,
        "body_ache": 0.8,
        "fatigue": 0.8,
        "headache": 0.7,
        "cough": 0.6,
        "chills": 0.6,
        "sore_throat": 0.4,
    },
    "dengue_risk": {
        "fever": 0.9,
        "body_ache": 0.8,
        "headache": 0.7,
        "skin_rash": 0.6,
        "fatigue": 0.5,
        "nausea": 0.4,
    },
    "gastroenteritis": {
        "nausea": 0.9,
        "abdominal_pain": 0.8,
        "diarrhea": 0.8,
        "fatigue": 0.5,
        "fever": 0.4,
        "dehydration": 0.3,
    },
    "cardiac_concern": {
        "chest_pain": 0.9,
        "breathlessness": 0.8,
        "sweating": 0.6,
        "dizziness": 0.5,
        "fatigue": 0.4,
        "nausea": 0.3,
        "palpitations": 0.7,
    },
    "allergic_reaction": {
        "skin_rash": 0.8,
        "nasal_congestion": 0.6,
        "cough": 0.5,
        "breathlessness": 0.4,
        "fatigue": 0.2,
        "watery_eyes": 0.7,
        "sneezing": 0.6,
    },
    # ── New conditions ────────────────────────────────
    "migraine": {
        "headache": 0.95,
        "nausea": 0.6,
        "dizziness": 0.5,
        "vision_changes": 0.7,
        "sensitivity_to_light": 0.8,
        "fatigue": 0.3,
    },
    "urinary_tract_infection": {
        "painful_urination": 0.9,
        "frequent_urination": 0.85,
        "abdominal_pain": 0.5,
        "fever": 0.4,
        "back_pain": 0.5,
        "fatigue": 0.3,
    },
    "bronchitis": {
        "cough": 0.9,
        "chest_pain": 0.5,
        "breathlessness": 0.6,
        "fatigue": 0.5,
        "fever": 0.3,
        "sore_throat": 0.4,
        "wheezing": 0.7,
    },
    "dehydration": {
        "dizziness": 0.7,
        "fatigue": 0.6,
        "headache": 0.5,
        "dry_mouth": 0.9,
        "dark_urine": 0.8,
        "dehydration": 0.9,
        "nausea": 0.3,
    },
    "anxiety_disorder": {
        "palpitations": 0.8,
        "breathlessness": 0.6,
        "sweating": 0.5,
        "dizziness": 0.5,
        "insomnia": 0.7,
        "trembling": 0.6,
        "chest_pain": 0.4,
        "fatigue": 0.5,
    },
    "food_poisoning": {
        "nausea": 0.9,
        "abdominal_pain": 0.8,
        "diarrhea": 0.9,
        "fever": 0.5,
        "chills": 0.4,
        "dehydration": 0.5,
        "fatigue": 0.4,
    },
    "hypertension_risk": {
        "headache": 0.6,
        "dizziness": 0.7,
        "vision_changes": 0.5,
        "chest_pain": 0.5,
        "breathlessness": 0.4,
        "palpitations": 0.6,
        "nosebleed": 0.4,
    },
    "anemia_risk": {
        "fatigue": 0.9,
        "dizziness": 0.7,
        "breathlessness": 0.6,
        "pale_skin": 0.8,
        "headache": 0.5,
        "palpitations": 0.5,
        "cold_hands": 0.4,
    },
    "asthma_exacerbation": {
        "breathlessness": 0.9,
        "wheezing": 0.9,
        "cough": 0.7,
        "chest_pain": 0.5,
        "fatigue": 0.3,
    },
    "diabetes_risk": {
        "frequent_urination": 0.8,
        "excessive_thirst": 0.8,
        "fatigue": 0.6,
        "vision_changes": 0.5,
        "weight_loss": 0.6,
        "slow_healing": 0.5,
    },
}
